# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:latest

    working_directory: /go/src/github.com/TWinsnes/awscreds
    steps:
      - checkout

      # build and test
      - run: go get -v -t -d ./...
      - run: go build -v
      - run: go test -v -race -cover ./...

  deploy:
    docker:
      - image: circleci/golang:latest

    worksing_directory: /go/src/github.com/TWinsnes/awscreds
    steps:
      - checkout

      - run: go get -v -t -d ./...

      # Only build additinoal 
      # build for macos
      - run: 
          name: Build for macOS
          environments:   
            GOOS: darwin
            GOARCH: amd64 
          command: |
            go build -v -o awscreds .
            mkdir output
            export version=$(./awscreds version | sed -e 's/Version: //')
            zip "output/awscreds_${version}_darwin.zip" awscreds

      # build windows 64 bit
      - run: 
          name: Build Windows 64bit
          environments: 
            GOOS: windows
            GOARCH: amd64
          command: | 
            go get github.com/inconshreveable/mousetrap
            go build -v -o awscreds.exe .
            export version=$(./awscreds version | sed -e 's/Version: //')
            zip "output/awscreds_${version}_win64.zip" awscreds.exe

      #build windows 32 bit
      - run: 
          name: Build Windows 32bit
          environments: 
            GOOS: windows
            GOARCH: 386
          command: |
            go build -v -o awscreds.exe .
            export version=$(./awscreds version | sed -e 's/Version: //')
            zip "output/awscreds_${version}_win32.zip" awscreds.exe
            pwd

      - store_artifacts:
          path: output
          
workflows:
  version: 2
  build_test_deploy:
    jobs:
      - build
      - deploy:
          requires: 
            - build
          # filters:
          #   branches:
          #     only: master
          #   tags:
          #     ignore: /.*/